HOMEWEB_BASE_URL = "https://homeweb.ca"
CUSTOMER_PORTAL_BASE_URL = "https://portal.homewoodhealth.com"
QUANTUM_API_BASE_URL = "https://api.homewoodhealth.io"

HOMEWEB_DOMAIN = "homeweb"
CUSTOMER_PORTAL_DOMAIN = "portal.homewoodhealth"
QUANTUM_API_DOMAIN = "api.homewoodhealth"
SENTIO_DOMAIN = "sentioapp"
LIFESTAGE_DOMAIN = "lifestage"
LIFESTYLE_DOMAIN = "healthycommunity"
